apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: akg4bcb44-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/akg4bcb44-java-quarkus-gitops